### PR TITLE
polars-expressions

### PR DESCRIPTION
**Pull request by ritchie46**
This adds a section about polars expressions

### CODE REVIEW

**Comment by carnarez** [comment]
The changes to the `Makefile` are due to the `_examples` -> `examples`.
And you can simply delete the `_images` folder.

**Comment by carnarez** [comment]
Seems the `.gitignore` still ignore `_outputs` but not `outputs`. My bad.

**Comment by carnarez** [comment]
> Seems the `.gitignore` still ignore `_outputs` but not `outputs`. My bad.

Same for the `make clean` recipe.

**Comment by ritchie46** [comment]
> Seems the `.gitignore` still ignores `_outputs` but not `outputs`. My bad.

Have fixed this.

**Pull request merged**
